### PR TITLE
MSHARED-806 - Upgrade plexus-utils 3.2.0

### PR DESCRIPTION
**Pull request by dineshbhagat**
changing version from 3.1.0 to 3.2.0

https://issues.apache.org/jira/browse/MSHARED-806

### CODE REVIEW

**Comment by khmarbaise** [comment]
Thanks for the contribution. Testing via CI... lets see what CI says https://builds.apache.org/job/maven-box/job/maven-file-management/job/MSHARED-806/

**Comment by dineshbhagat** [comment]
[Test-Result](https://builds.apache.org/job/maven-box/job/maven-file-management/job/MSHARED-806/1/testReport/)
[Build-Success](https://builds.apache.org/job/maven-box/job/maven-file-management/job/MSHARED-806/1/console)

**Comment by khmarbaise** [comment]
Thanks for your contribution. Change is on master.

**Comment by jira-importer** [comment]
Resolve #66

**Pull request closed without merging**
