### PR TITLE
[MSHARED-1203] Move tests to nio

### PR DESCRIPTION
**Pull request by slachiewicz**
@elharo feel free to continue working on this or do from scrach.
Here is only simple switch to NIO and this also doesnt work on windows.

### CODE REVIEW

**Review by elharo — COMMENTED** [review]
I don't have a windows box handy to debug this, I'm afraid. I'm not sure why it doesn't work on windows. As far as I know these nio methods should work on windows

**Comment by elharo** [comment]
```
[INFO] 
Error:  Errors: 
Error:    FileSetUtilsTest.tearDown:55 � DirectoryNotEmpty D:\a\maven-file-management\maven-file-management\target\test-directories\testDeleteDontFollowSymlinks\testDeleteDontFollowSymlinks
Error:    FileSetUtilsTest.tearDown:55 � DirectoryNotEmpty D:\a\maven-file-management\maven-file-management\target\test-directories\testIncludesDontFollowSymlinks\testIncludesDontFollowSymlinks
[INFO] 
```

so this could mean either the delete directory method works on a non-empty directory in Unix but not Windows, or the somehow on windows files are left behind that have already been deleted on unix

**Comment by elharo** [comment]
So here's a hypothesis: the way this test creates test directories is borked. Instead it should use a JUnit TemporaryFolder Rule and let that handle the cleanup:

https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html

**Comment by elharo** [comment]
same problem

```
 Error:  org.apache.maven.shared.model.fileset.util.FileSetUtilsTest.testIncludesDontFollowSymlinks  Time elapsed: 0.062 s  <<< ERROR!
java.nio.file.DirectoryNotEmptyException: C:\Users\RUNNER~1\AppData\Local\Temp\junit5253007099003736157\target\test-directories\testIncludesDontFollowSymlinks\testIncludesDontFollowSymlinks
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:266)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at org.apache.maven.shared.model.fileset.util.FileSetUtilsTest.tearDown(FileSetUtilsTest.java:57)
```

**Comment by elharo** [comment]
@slachiewicz It is now finally passing

**Comment by slachiewicz** [comment]
no longer neeed

**Comment by jira-importer** [comment]
Resolve #82

**Pull request closed without merging**
